# Classical Latin Lorem Ipsum Dictionary (la)

sentences = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Aenean interdum convallis ex, eget gravida nisl cursus id.",
    "Proin elementum dolor nec nisi feugiat, non hendrerit lacus laoreet.",
    "Cras dictum, ante eu molestie elementum, tellus eros dictum nunc, id pulvinar turpis lectus quis sem.",
    "Ut eget elit rhoncus, lacinia diam vel, elementum sem.",
    "Fusce sollicitudin rhoncus ante, id tempor magna accumsan nec.",
    "Donec quis sem sed ex feugiat auctor.",
    "In in accumsan nibh, sit amet efficitur turpis.",
    "In at eleifend nulla, ac feugiat erat.",
    "Mauris in lectus non sapien mattis elementum vitae id est.",
    "Duis a finibus augue, sit amet pretium nunc.",
    "Praesent porta est eu lorem tincidunt auctor.",
    "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
    "Et harum quidem rerum facilis est et expedita distinctio.",
    "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
    "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
    "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
    "Curabitur rhoncus magna eget ante rhoncus pretium.",
    "Nulla varius nibh sit amet nisl efficitur, ut varius risus pulvinar.",
    "Sed in interdum erat, sed pulvinar lorem.",
    "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
    "Praesent tristique rhoncus justo, et ultrices diam eleifend egestas.",
    "Vivamus facilisis, nisl sit amet hendrerit imperdiet, felis sapien feugiat velit, at varius magna orci nec tellus.",
    "Morbi pretium est id pretium sollicitudin.",
    "Quisque at leo sed nisi congue sodales et nec ex.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "Integer porta est a erat facilisis, ac viverra ipsum hendrerit.",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae."
]
