# Specialized Domain Lexicons for Prolixo: Ecology, Law, Medicine, Mining, Politics, Technology

THEME_DICTS = {
    "pt": {
        "business": {
            "n_ms": ["planejamento estratégico", "plano de negócios", "fluxo de caixa", "retorno sobre o investimento", "posicionamento de mercado", "conselho de administração", "equilíbrio financeiro", "acordo comercial", "orçamento operacional", "valuation projetado", "capital de giro", "valor de mercado", "crescimento sustentável", "comitê executivo", "desempenho corporativo"],
            "n_fs": ["estratégia corporativa", "gestão de riscos", "margem de lucro", "governança corporativa", "vantagem competitiva", "sinergia operacional", "análise de viabilidade", "reestruturação societária", "eficiência operacional", "fusão empresarial", "tomada de decisão", "visão estratégica", "rentabilidade financeira"],
            "n_mp": ["indicadores financeiros", "principais stakeholders", "ativos estratégicos", "resultados operacionais", "planos de contingência", "vetores de crescimento", "mercados emergentes", "fundos de investimento", "modelos de receita", "custos operacionais"],
            "n_fp": ["diretrizes estratégicas", "oportunidades de mercado", "metas corporativas", "projeções financeiras", "alianças comerciais", "estruturas de capital", "vantagens competitivas", "operações de crédito"],
            "adj_ms": [" estratégico", " corporativo", " financeiro", " rentável", " competitivo", " operacional", " escalável", " lucrativo", " comercial"],
            "adj_fs": [" estratégica", " corporativa", " financeira", " rentável", " competitiva", " operacional", " escalável", " lucrativa", " comercial"],
            "adj_mp": [" estratégicos", " corporativos", " financeiros", " rentáveis", " competitivos", " operacionais", " escaláveis", " lucrativos"],
            "adj_fp": [" estratégicas", " corporativas", " financeiras", " rentáveis", " competitivas", " operacionais", " escaláveis", " lucrativas"],
            "v_trans_s": ["maximiza ", "alavanca ", "otimiza ", "consolida ", "potencializa ", "viabiliza ", "estrutura ", "impulsiona ", "mitiga ", "incorpora ", "implementa "],
            "v_trans_p": ["maximizam ", "alavancam ", "otimizam ", "consolidam ", "potencializam ", "viabilizam ", "estruturam ", "impulsionam ", "mitigam ", "incorporam ", "implementam "],
            "v_intrans_s": ["maximiza o retorno sobre o investimento", "assegura a solidez financeira", "fortalece o posicionamento de mercado", "gera valor para os acionistas", "otimiza a rentabilidade operacional", "impulsiona a eficiência dos negócios"],
            "v_intrans_p": ["maximizam o retorno sobre o investimento", "asseguram a solidez financeira", "fortalecem o posicionamento de mercado", "geram valor para os acionistas", "otimizam a rentabilidade operacional", "impulsionam a eficiência dos negócios"]
        },
        "ecology": {
            "n_ms": ["crédito de carbono", "bioma frágil", "ecossistema sustentável", "impacto ecológico", "manejo florestal", "reflorestamento consciente", "desenvolvimento sustentável", "inventário de emissões", "recurso hídrico", "balanço energético", "topo da cadeia trófica", "habitat natural", "atropelamento de fauna", "uso do solo", "mosaico de paisagens", "uso e cobertura da terra", "bem-estar animal"],
            "n_fs": ["transição energética", "pegada de carbono", "biodiversidade preservada", "conservação ambiental", "economia circular", "neutralidade climática", "gestão de resíduos", "sustentabilidade ecológica", "matriz renovável", "avaliação de impacto ambiental", "reserva extrativista", "conectividade ecológica", "fragmentação de habitats", "fragmentação florestal", "conectividade paisagística"],
            "n_mp": ["recursos naturais", "ecossistemas locais", "indicadores ambientais", "créditos de carbono", "padrões de sustentabilidade", "habitats protegidos", "resíduos sólidos", "serviços ecossistêmicos", "biomas ameaçados", "atropelamentos de fauna", "mosaicos de paisagens"],
            "n_fp": ["energias renováveis", "metas de descarbonização", "políticas ambientais", "áreas de preservação", "práticas sustentáveis", "fontes de energia limpa", "emissões de gases de efeito estufa", "medidas mitigadoras", "ações de bem-estar animal"],
            "adj_ms": [" sustentável", " ecológico", " de baixo carbono", " renovável", " de impacto neutro", " biodegradável", " ecossistêmico", " descarbonizado"],
            "adj_fs": [" sustentável", " ecológica", " de baixo carbono", " renovável", " de impacto neutro", " biodegradável", " ecossistêmica", " descarbonizada"],
            "adj_mp": [" sustentáveis", " ecológicos", " de baixo carbono", " renováveis", " de impacto neutro", " biodegradáveis", " ecossistêmicos"],
            "adj_fp": [" sustentáveis", " ecológicas", " de baixo carbono", " renováveis", " de impacto neutro", " biodegradáveis", " ecossistêmicas"],
            "v_trans_s": ["preserva ", "mitiga ", "regenera ", "descarboniza ", "conserva ", "restaura ", "reabilita ", "despolui ", "protege ", "incorpora ", "implementa "],
            "v_trans_p": ["preservam ", "mitigam ", "regeneram ", "descarbonizam ", "conservam ", "restauram ", "reabilitam ", "despoluem ", "protegem ", "incorporam ", "implementam "],
            "v_intrans_s": ["promove a neutralidade climática", "reduz o impacto ambiental", "fortalece a biodiversidade", "assegura o equilíbrio ecológico", "regenera os ecossistemas nativos", "reduz o atropelamento de fauna", "promove o bem-estar animal", "assegura a conectividade ecológica", "mitiga a fragmentação de habitats"],
            "v_intrans_p": ["promovem a neutralidade climática", "reduzem o impacto ambiental", "fortalecem a biodiversidade", "asseguram o equilíbrio ecológico", "regeneram os ecossistemas nativos", "reduzem o atropelamento de fauna", "promovem o bem-estar animal", "asseguram a conectividade ecológica", "mitigam a fragmentação de habitats"]
        },
        "law": {
            "n_ms": ["devido processo legal", "ordenamento jurídico", "litígio judicial", "amparo legal", "parecer jurídico", "vício formal", "recurso cabível", "acórdão proferido", "provimento jurisdicional", "agravo de instrumento", "juízo de admissibilidade", "trânsito em julgado"],
            "n_fs": ["jurisprudência consolidada", "segurança jurídica", "norma constitucional", "instrução processual", "súmula vinculante", "presunção de inocência", "cláusula pétrea", "tutela de urgência", "medida cautelar", "petição inicial", "coisa julgada"],
            "n_mp": ["direitos fundamentais", "prazos processuais", "precedentes judiciais", "autos do processo", "dispositivos legais", "recursos tempestivos", "honorários advocatícios", "atos ordinatórios", "embargos de declaração"],
            "n_fp": ["prerrogativas advocatícias", "garantias constitucionais", "normas jurídicas", "decisões interlocutórias", "medidas cautelares", "razões recursais", "petições intermediárias"],
            "adj_ms": [" jurídico", " constitucional", " processual", " vinculante", " tempestivo", " incontestável", " infraconstitucional", " jurisprudencial", " líqüido e certo"],
            "adj_fs": [" jurídica", " constitucional", " processual", " vinculante", " tempestiva", " incontestável", " infraconstitucional", " jurisprudencial", " líqüida e certa"],
            "adj_mp": [" jurídicos", " constitucionais", " processuais", " vinculantes", " tempestivos", " incontestáveis", " infraconstitucionais"],
            "adj_fp": [" jurídicas", " constitucionais", " processuais", " vinculantes", " tempestivas", " incontestáveis", " infraconstitucionais"],
            "v_trans_s": ["fundamenta ", "ratifica ", "pacifica ", "prescreve ", "regulamenta ", "assenta ", "impulsiona ", "defere ", "incorpora ", "implementa "],
            "v_trans_p": ["fundamentam ", "ratificam ", "pacificam ", "prescrevem ", "regulamentam ", "assentam ", "impulsionam ", "deferem ", "incorporam ", "implementam "],
            "v_intrans_s": ["garante a segurança jurídica", "resguarda o devido processo legal", "respeita o texto constitucional", "consolida o entendimento jurisprudencial", "viabiliza a ampla defesa"],
            "v_intrans_p": ["garantem a segurança jurídica", "resguardam o devido processo legal", "respeitam o texto constitucional", "consolidam o entendimento jurisprudencial", "viabilizam a ampla defesa"]
        },
        "medicine": {
            "n_ms": ["diagnóstico clínico", "protocolo terapêutico", "ensaio clínico", "marcador biológico", "quadro sintomático", "tratamento profilático", "exame laboratorial", "prognóstico médico", "agente patogênico", "transplante autólogo", "plano de cuidados"],
            "n_fs": ["terapia profilática", "farmacovigilância", "conduta médica", "anamnese detalhada", "imunidade celular", "fisiopatologia", "resposta imune", "eficácia terapêutica", "propedêutica médica", "remissão completa", "dose terapêutica"],
            "n_mp": ["ensaios clínicos", "marcadores biológicos", "ensaios randomizados", "sintomas característicos", "agentes patogênicos", "parâmetros fisiológicos", "achados radiológicos", "tratamentos paliativos"],
            "n_fp": ["respostas imunológicas", "terapias inovadoras", "intervenções cirúrgicas", "evidências científicas", "medidas profiláticas", "reações adversas", "diretrizes clínicas"],
            "adj_ms": [" terapêutico", " clínico", " profilático", " fisiológico", " patogênico", " multidisciplinar", " assintomático", " etiológico", " farmacológico"],
            "adj_fs": [" terapêutica", " clínica", " profilática", " fisiológica", " patogênica", " multidisciplinar", " assintomática", " etiológica", " farmacológica"],
            "adj_mp": [" terapêuticos", " clínicos", " profiláticos", " fisiológicos", " patogênicos", " multidisciplinares", " assintomáticos"],
            "adj_fp": [" terapêuticas", " clínicas", " profiláticas", " fisiológicas", " patogênicas", " multidisciplinares", " assintomáticas"],
            "v_trans_s": ["diagnostica ", "sintetiza ", "atenua ", "reabilita ", "prescreve ", "estabiliza ", "modula ", "inibe ", "combate ", "incorpora ", "implementa "],
            "v_trans_p": ["diagnosticam ", "sintetizam ", "atenuam ", "rehabilitam ", "prescrevem ", "estabilizam ", "modulam ", "inibem ", "combatem ", "incorporam ", "implementam "],
            "v_intrans_s": ["potencializa a resposta imune", "garante a eficácia terapêutica", "combate a progressão da patologia", "assegura a recuperação clínica", "reduz a morbidade infantil"],
            "v_intrans_p": ["potencializam a resposta imune", "garantem a eficácia terapêutica", "combatem a progressão da patologia", "asseguram a recuperação clínica", "reduzem a morbidade infantil"]
        },
        "mining": {
            "n_ms": ["beneficiamento de minério", "teor de jazida", "recuo geológico", "plano de lavra", "mapeamento geotécnico", "escoamento logístico", "processamento mineral", "depósito sedimentar", "teor de corte", "duto de rejeitos", "aluguel de equipamentos", "dique", "dique de contenção", "estudo de estabilidade da cava", "engenheiro de registro", "estudo de ruptura hipotética", "estudo de impacto ambiental"],
            "n_fs": ["lavra subterrânea", "barragem de rejeitos", "prospecção geológica", "lavra a céu aberto", "exploração mineral", "geotecnia operacional", "jazida lavrável", "recuperação de mina", "galeria de extração", "sondagem rotativa", "mineração responsável", "pilha de estéril", "cava", "zona de autossalvamento"],
            "n_mp": ["rejeitos minerais", "teores de corte", "parâmetros geotécnicos", "corpos mineralizados", "recursos lavráveis", "métodos de extração", "concentrados minerais", "testes hidrogeológicos", "protocolos", "protocolos operacionais", "protocolos ambientais", "diques de segurança", "engenheiros de registro", "estudos de ruptura hipotética", "estudos de impacto ambiental"],
            "n_fp": ["barragens de contenção", "jazidas minerais", "operações de lavra", "reservas provadas", "estruturas geotécnicas", "rochas hospedeiras", "escavações mecânicas", "pilhas de estéril", "cavas de lavra", "zonas de autossalvamento"],
            "adj_ms": [" mineral", " geotécnico", " geológico", " extrativo", " de alta qualidade", " lavrável", " hidrogeológico", " sedimentar"],
            "adj_fs": [" mineral", " geotécnica", " geológica", " extrativa", " de alta qualidade", " lavrável", " hidrogeológica", " sedimentar"],
            "adj_mp": [" minerais", " geotécnicos", " geológicos", " extrativos", " lavráveis", " hidrogeológicos"],
            "adj_fp": [" minerais", " geotécnicas", " geológicas", " extrativas", " lavráveis", " hidrogeológicas"],
            "v_trans_s": ["extrai ", "beneficia ", "mapeia ", "processa ", "estabiliza ", "otimiza ", "perfura ", "escava ", "amostra ", "incorpora ", "implementa "],
            "v_trans_p": ["extraem ", "beneficiam ", "mapeiam ", "processam ", "estabilizam ", "otimizam ", "perfuram ", "escavam ", "amostram ", "incorporam ", "implementam "],
            "v_intrans_s": ["aumenta a recuperação metalúrgica", "assegura a estabilidade geotécnica", "otimiza o ciclo de lavra", "maximiza o teor da reserva", "mitiga os riscos de ruptura", "promove a mineração responsável"],
            "v_intrans_p": ["aumentam a recuperação metalúrgica", "asseguram a estabilidade geotécnica", "otimizam o ciclo de lavra", "maximizam o teor da reserva", "mitigam os riscos de ruptura", "promovem a mineração responsável"]
        },
        "politics": {
            "n_ms": ["pacto federativo", "processo legislativo", "orçamento participativo", "cenário eleitoral", "debate parlamentar", "pleito eleitoral", "acordo político", "projeto de lei", "sistema multipartidário", "quórum qualificado", "plenário da câmara"],
            "n_fs": ["bancada parlamentar", "reforma institucional", "coalizão partidária", "articulação política", "soberania popular", "política pública", "diplomacia multilateral", "representatividade democrática", "emenda constitucional", "casa legislativa"],
            "n_mp": ["direitos civis", "acordos bilaterais", "projetos de lei", "debates públicos", "pactos institucionais", "mandatos representativos", "partidos políticos", "pleitos eleitorais"],
            "n_fp": ["políticas públicas", "reformas estruturais", "coalizões partidárias", "instâncias de poder", "diretrizes governamentais", "emendas parlamentares", "comissões temáticas"],
            "adj_ms": [" parlamentar", " legislativo", " democrático", " institucional", " governamental", " multipartidário", " suprapartidário", " diplomático"],
            "adj_fs": [" parlamentar", " legislativa", " democrática", " institucional", " governamental", " multipartidária", " suprapartidária", " diplomática"],
            "adj_mp": [" parlamentares", " legislativos", " democráticos", " institucionais", " governamentais", " multipartidários"],
            "adj_fp": [" parlamentares", " legislativas", " democráticas", " institucionais", " governamentais", " multipartidárias"],
            "v_trans_s": ["articula ", "tramita ", "promulga ", "sanciona ", "debate ", "pactua ", "delibera ", "vota ", "negocia ", "incorpora ", "implementa "],
            "v_trans_p": ["articulam ", "tramitam ", "promulgam ", "sancionam ", "debatem ", "pactuam ", "deliberam ", "votam ", "negociam ", "incorporam ", "implementam "],
            "v_intrans_s": ["fortalece a representatividade democrática", "promove a estabilidade institucional", "assegura o exercício da cidadania", "consolida a participação popular", "viabiliza o consenso político"],
            "v_intrans_p": ["fortalecem a representatividade democrática", "promovem a estabilidade institucional", "asseguram o exercício da cidadania", "consolidam a participação popular", "viabilizam o consenso político"]
        },
        "technology": {
            "n_ms": ["modelo estrutural", "planejamento estratégico", "sprint de inovação", "ecossistema de negócios", "pipeline de integração", "benchmark de mercado", "vetor de transformação", "dashboard de KPIs", "algoritmo preditivo", "servidor distribuído", "cluster de computação"],
            "n_fs": ["governança corporativa", "disrupção tecnológica", "metodologia ágil", "transformação digital", "arquitetura de microsserviços", "experiência do usuário", "inteligência preditiva", "matriz de priorização", "infraestrutura em nuvem", "linguagem de programação"],
            "n_mp": ["fluxos de trabalho", "gargalos operacionais", "mecanismos de controle", "sistemas legados", "requisitos não-funcionais", "drivers de crescimento", "microsserviços escaláveis", "bancos de dados relacionais"],
            "n_fp": ["atividades operacionais", "metas estratégicas", "ferramentas tecnológicas", "competências essenciais", "soluções de ponta a ponta", "capacidades analíticas", "APIs RESTful", "filas de mensagens"],
            "adj_ms": [" resiliente", " adaptativo", " sustentável", " disruptivo", " otimizado", " escalável", " inovador", " orientado a dados", " distribuído", " contenerizado"],
            "adj_fs": [" resiliente", " adaptativa", " sustentável", " disruptiva", " otimizada", " escalável", " inovadora", " orientada a dados", " distribuída", " contenerizada"],
            "adj_mp": [" resilientes", " adaptativos", " sustentáveis", " disruptivos", " otimizados", " escaláveis", " inovadores", " orientados a dados", " distribuídos"],
            "adj_fp": [" resilientes", " adaptativas", " sustentáveis", " disruptivas", " otimizadas", " escaláveis", " inovadoras", " orientadas a dados", " distribuídas"],
            "v_trans_s": ["exige ", "obriga ", "impulsiona ", "otimiza ", "viabiliza ", "sustenta ", "alavanca ", "desbloqueia ", "orquestra ", "compila ", "incorpora ", "implementa "],
            "v_trans_p": ["exigem ", "obrigam ", "impulsionam ", "otimizam ", "viabilizam ", "sustentam ", "alavancam ", "desbloqueiam ", "orquestram ", "compilam ", "incorporam ", "implementam "],
            "v_intrans_s": ["evolui de forma contínua", "progride a passos largos", "se consolida no mercado", "gera valor agregado de longo prazo", "reduz a latência operacional"],
            "v_intrans_p": ["evoluem de forma contínua", "progridem a passos largos", "se consolidam no mercado", "geram valor agregado de longo prazo", "reduzem a latência operacional"]
        }
    },
    "en": {
        "business": {
            "n_s": ["strategic planning", "business plan", "cash flow", "return on investment", "market positioning", "board of directors", "financial equilibrium", "commercial agreement", "operating budget", "projected valuation", "working capital", "corporate governance", "competitive advantage", "operational synergy", "feasibility analysis", "strategic decision"],
            "n_p": ["key stakeholders", "financial metrics", "operating margins", "growth vectors", "revenue models", "emerging markets", "strategic partnerships", "capital allocations", "quarterly earnings", "operating expenses", "core competencies"],
            "adj": ["strategic", "corporate", "financial", "profitable", "competitive", "operational", "scalable", "lucrative", "commercial", "enterprise-grade"],
            "v_trans_s": ["maximizes ", "leverages ", "optimizes ", "consolidates ", "enhances ", "enables ", "structures ", "drives ", "mitigates ", "scales "],
            "v_trans_p": ["maximize ", "leverage ", "optimize ", "consolidate ", "enhance ", "enable ", "structure ", "drive ", "mitigate ", "scale "],
            "v_intrans_s": ["maximizes return on investment", "delivers long-term shareholder value", "strengthens market position", "ensures financial resilience", "drives operational excellence", "accelerates business growth"],
            "v_intrans_p": ["maximize return on investment", "deliver long-term shareholder value", "strengthen market position", "ensure financial resilience", "drive operational excellence", "accelerate business growth"]
        },
        "ecology": {
            "n_s": ["carbon credit", "fragile biome", "sustainable ecosystem", "ecological impact", "forest management", "conscious reforestation", "sustainable development", "emissions inventory", "energy transition", "carbon footprint", "biodiversity conservation", "circular economy", "renewable grid", "climate resilience", "habitat protection", "waste recovery"],
            "n_p": ["natural resources", "local ecosystems", "environmental indicators", "carbon credits", "sustainability standards", "protected habitats", "renewable energies", "decarbonization goals", "ecological reserves", "green technologies", "conservation practices"],
            "adj": ["sustainable", "ecological", "low-carbon", "renewable", "carbon-neutral", "biodegradable", "environmentally-sound", "climate-resilient", "bio-based", "regenerative"],
            "v_trans_s": ["preserves ", "mitigates ", "regenerates ", "decarbonizes ", "conserves ", "restores ", "rehabilitates ", "protects ", "sequesters "],
            "v_trans_p": ["preserve ", "mitigate ", "regenerate ", "decarbonize ", "conserve ", "restore ", "rehabilitate ", "protect ", "sequester "],
            "v_intrans_s": ["promotes climate neutrality", "reduces environmental impact", "strengthens biodiversity", "ensures ecological balance", "fosters environmental stewardship"],
            "v_intrans_p": ["promote climate neutrality", "reduce environmental impact", "strengthen biodiversity", "ensure ecological balance", "foster environmental stewardship"]
        },
        "law": {
            "n_s": ["due process of law", "legal order", "judicial litigation", "legal protection", "legal opinion", "formal defect", "constitutional norm", "binding precedent", "established jurisprudence", "legal certainty", "statutory framework", "judicial decree", "interlocutory appeal", "burden of proof", "legal remedy"],
            "n_p": ["fundamental rights", "procedural deadlines", "judicial precedents", "court records", "statutory provisions", "constitutional guarantees", "legal prerogatives", "attorney fees", "binding rulings", "evidentiary standards"],
            "adj": ["legal", "constitutional", "procedural", "binding", "statutory", "uncontestable", "judicial", "jurisprudence-based", "enforceable", "legitimate"],
            "v_trans_s": ["substantiates ", "ratifies ", "settles ", "prescribes ", "regulates ", "establishes ", "enforces ", "adjudicates ", "upholds "],
            "v_trans_p": ["substantiate ", "ratify ", "settle ", "prescribe ", "regulate ", "establish ", "enforce ", "adjudicate ", "uphold "],
            "v_intrans_s": ["guarantees legal certainty", "safeguards due process", "upholds constitutional norms", "consolidates judicial understanding", "protects fundamental rights"],
            "v_intrans_p": ["guarantee legal certainty", "safeguard due process", "uphold constitutional norms", "consolidate judicial understanding", "protect fundamental rights"]
        },
        "medicine": {
            "n_s": ["clinical diagnosis", "therapeutic protocol", "clinical trial", "biological marker", "symptomatic profile", "prophylactic treatment", "laboratory examination", "medical prognosis", "pharmacovigilance", "cellular immunity", "disease pathophysiology", "surgical intervention", "therapeutic efficacy", "autologous transplant"],
            "n_p": ["clinical trials", "biological markers", "randomized trials", "characteristic symptoms", "pathogenic agents", "physiological parameters", "immunological responses", "therapeutic regimens", "adverse reactions", "diagnostic guidelines"],
            "adj": ["therapeutic", "clinical", "prophylactic", "physiological", "pathogenic", "multidisciplinary", "asymptomatic", "pharmacological", "etiological", "diagnostic"],
            "v_trans_s": ["diagnoses ", "synthesizes ", "attenuates ", "rehabilitates ", "prescribes ", "stabilizes ", "modulates ", "inhibits ", "alleviates "],
            "v_trans_p": ["diagnose ", "synthesize ", "attenuate ", "rehabilitate ", "prescribe ", "stabilize ", "modulate ", "inhibit ", "alleviate "],
            "v_intrans_s": ["enhances immune response", "ensures therapeutic efficacy", "combats pathology progression", "secures clinical recovery", "optimizes patient outcome"],
            "v_intrans_p": ["enhance immune response", "ensure therapeutic efficacy", "combat pathology progression", "secure clinical recovery", "optimize patient outcome"]
        },
        "mining": {
            "n_s": ["ore processing", "deposit grade", "geological retreat", "mining plan", "geotechnical mapping", "mineral processing", "sedimentary deposit", "underground mining", "tailings dam", "mineral exploration", "cutoff grade", "opencast mine", "slurry pipeline", "rotary drilling"],
            "n_p": ["mineral tailings", "cutoff grades", "geotechnical parameters", "mineralized bodies", "extractable reserves", "extraction methods", "ore concentrates", "hydrogeological surveys", "host rocks"],
            "adj": ["mineral", "geotechnical", "geological", "extractive", "high-grade", "sustainable", "hydrogeological", "sedimentary", "open-pit", "underground"],
            "v_trans_s": ["extracts ", "processes ", "maps ", "beneficiates ", "stabilizes ", "optimizes ", "drills ", "excavates ", "samples "],
            "v_trans_p": ["extract ", "process ", "map ", "beneficiate ", "stabilize ", "optimize ", "drill ", "excavate ", "sample "],
            "v_intrans_s": ["increases metallurgical recovery", "ensures geotechnical stability", "optimizes the mining cycle", "maximizes deposit value", "mitigates slope failure risks"],
            "v_intrans_p": ["increase metallurgical recovery", "ensure geotechnical stability", "optimize the mining cycle", "maximize deposit value", "mitigate slope failure risks"]
        },
        "politics": {
            "n_s": ["federal pact", "legislative process", "participatory budgeting", "electoral landscape", "parliamentary debate", "political agreement", "bill draft", "parliamentary caucus", "institutional reform", "party coalition", "constitutional amendment", "diplomatic protocol", "democratic representation", "voting quorum"],
            "n_p": ["civil rights", "bilateral agreements", "legislative bills", "public debates", "institutional pacts", "representative mandates", "political parties", "parliamentary committees", "diplomatic channels"],
            "adj": ["parliamentary", "legislative", "democratic", "institutional", "governmental", "bipartisan", "diplomatic", "constitutional", "multilateral"],
            "v_trans_s": ["articulates ", "promulgates ", "enacts ", "debates ", "sanctions ", "negotiates ", "deliberates ", "ratifies ", "sponsors "],
            "v_trans_p": ["articulate ", "promulgate ", "enact ", "debate ", "sanction ", "negotiate ", "deliberate ", "ratify ", "sponsor "],
            "v_intrans_s": ["strengthens democratic representation", "promotes institutional stability", "ensures civic participation", "consolidates popular sovereignty", "fosters political consensus"],
            "v_intrans_p": ["strengthen democratic representation", "promote institutional stability", "ensure civic participation", "consolidate popular sovereignty", "foster political consensus"]
        },
        "technology": {
            "n_s": ["business model", "strategic planning", "digital transformation", "microservices architecture", "cloud computing", "machine learning", "artificial intelligence", "integration pipeline", "data engineering", "cybersecurity framework", "scalable infrastructure", "automated workflow", "API gateway"],
            "n_p": ["workflows", "operational bottlenecks", "control mechanisms", "legacy systems", "non-functional requirements", "growth drivers", "microservices", "relational databases", "cloud clusters", "containerized deployments"],
            "adj": ["resilient", "adaptive", "sustainable", "disruptive", "optimized", "scalable", "innovative", "data-driven", "distributed", "containerized", "cloud-native"],
            "v_trans_s": ["demands ", "requires ", "drives ", "optimizes ", "enables ", "sustains ", "leverages ", "unlocks ", "orchestrates ", "deploys "],
            "v_trans_p": ["demand ", "require ", "drive ", "optimize ", "enable ", "sustain ", "leverage ", "unlock ", "orchestrate ", "deploy "],
            "v_intrans_s": ["evolves continuously", "progresses rapidly", "consolidates in the market", "delivers long-term value", "reduces operational latency"],
            "v_intrans_p": ["evolve continuously", "progress rapidly", "consolidate in the market", "deliver long-term value", "reduce operational latency"]
        }
    },
    "es": {
        "business": {
            "n_ms": ["planeamiento estratégico", "plan de negocios", "flujo de caja", "retorno de la inversión", "posicionamiento de mercado", "consejo de administración", "equilibrio financiero", "acuerdo comercial", "presupuesto operativo", "capital de trabajo", "crecimiento sostenible", "rendimiento corporativo"],
            "n_fs": ["estrategia corporativa", "gestión de riesgos", "margen de rentabilidad", "gobernanza corporativa", "ventaja competitiva", "sinergia operativa", "eficiencia financiera", "visión estratégica", "rentabilidad sostenida"],
            "n_mp": ["indicadores financieros", "principales accionistas", "activos estratégicos", "resultados operativos", "planes de contingencia", "mercados emergentes", "fondos de inversión", "costes operativos"],
            "n_fp": ["directrices estratégicas", "oportunidades de mercado", "metas corporativas", "proyecciones financieras", "alianzas comerciales", "ventajas competitivas"],
            "adj_ms": [" estratégico", " corporativo", " financiero", " rentable", " competitivo", " operativo", " escalable", " comercial"],
            "adj_fs": [" estratégica", " corporativa", " financiera", " rentable", " competitiva", " operativa", " escalable", " comercial"],
            "adj_mp": [" estratégicos", " corporativos", " financieros", " rentables", " competitivos", " operativos", " escalables"],
            "adj_fp": [" estratégicas", " corporativas", " financieras", " rentables", " competitivas", " operativas", " escalables"],
            "v_trans_s": ["maximiza ", "apalanca ", "optimiza ", "consolida ", "potencia ", "viabiliza ", "impulsa ", "mitiga "],
            "v_trans_p": ["maximizan ", "apalancan ", "optimizan ", "consolidan ", "potencian ", "viabilizan ", "impulsan ", "mitigan "],
            "v_intrans_s": ["maximiza el retorno de la inversión", "asegura la solidez financiera", "fortalece el posicionamiento en el mercado", "genera valor a largo plazo"],
            "v_intrans_p": ["maximizan el retorno de la inversión", "aseguran la solidez financiera", "fortalecen el posicionamiento en el mercado", "generan valor a largo plazo"]
        },
        "ecology": {
            "n_ms": ["crédito de carbono", "bioma frágil", "ecosistema sostenible", "impacto ecológico", "manejo forestal", "desarrollo sostenible", "inventario de emisiones", "recurso hídrico", "balance energético", "hábitat natural"],
            "n_fs": ["transición energética", "huella de carbono", "biodiversidad preservada", "conservación ambiental", "economía circular", "neutralidad climática", "gestión de residuos", "sostenibilidad ecológica", "matriz renovable"],
            "n_mp": ["recursos naturales", "ecosistemas locales", "indicadores ambientales", "créditos de carbono", "hábitats protegidos", "residuos sólidos", "servicios ecosistémicos"],
            "n_fp": ["energías renovables", "metas de descarbonización", "políticas ambientales", "áreas de preservación", "prácticas sostenibles", "fuentes limpias"],
            "adj_ms": [" sostenible", " ecológico", " de bajo carbono", " renovable", " de impacto neutro", " biodegradable", " ecosistémico"],
            "adj_fs": [" sostenible", " ecológica", " de bajo carbono", " renovable", " de impacto neutro", " biodegradable", " ecosistémica"],
            "adj_mp": [" sostenibles", " ecológicos", " de bajo carbono", " renovables", " de impacto neutro", " biodegradables"],
            "adj_fp": [" sostenibles", " ecológicas", " de bajo carbono", " renovables", " de impacto neutro", " biodegradables"],
            "v_trans_s": ["preserva ", "mitiga ", "regenera ", "descarboniza ", "conserva ", "restaura ", "protege ", "rehabilita "],
            "v_trans_p": ["preservan ", "mitigan ", "regeneran ", "descarbonizan ", "conservan ", "restauran ", "protegen ", "rehabilitan "],
            "v_intrans_s": ["promueve la neutralidad climática", "reduce el impacto ambiental", "fortalece la biodiversidad", "asegura el equilibrio ecológico"],
            "v_intrans_p": ["promueven la neutralidad climática", "reducen el impacto ambiental", "fortalecen la biodiversidad", "aseguran el equilibrio ecológico"]
        },
        "law": {
            "n_ms": ["debido proceso legal", "ordenamiento jurídico", "litigio judicial", "amparo legal", "dictamen jurídico", "vicio formal", "recurso procedente", "auto judicial", "proveído jurisdiccional", "pronunciamiento definitivo"],
            "n_fs": ["jurisprudencia consolidada", "seguridad jurídica", "norma constitucional", "instrucción procesal", "presunción de inocencia", "tutela de urgencia", "medida cautelar", "petición inicial", "cosa juzgada"],
            "n_mp": ["derechos fundamentales", "plazos procesales", "precedentes judiciales", "fundamentos legales", "recursos oportunos", "honorarios profesionales"],
            "n_fp": ["garantías constitucionales", "normas jurídicas", "decisiones interlocutorias", "medidas cautelares", "pretensiones jurídicas"],
            "adj_ms": [" jurídico", " constitucional", " procesal", " vinculante", " ineludible", " tempestivo", " jurisprudencial"],
            "adj_fs": [" jurídica", " constitucional", " procesal", " vinculante", " ineludible", " tempestiva", " jurisprudencial"],
            "adj_mp": [" jurídicos", " constitucionales", " procesales", " vinculantes", " ineludibles", " tempestivos"],
            "adj_fp": [" jurídicas", " constitucionales", " procesales", " vinculantes", " ineludibles", " tempestivas"],
            "v_trans_s": ["fundamenta ", "ratifica ", "pacifica ", "prescribe ", "reglamenta ", "asienta ", "defiende ", "avala "],
            "v_trans_p": ["fundamentan ", "ratifican ", "pacifican ", "prescriben ", "reglamentan ", "asientan ", "defienden ", "avalan "],
            "v_intrans_s": ["garantiza la seguridad jurídica", "resguarda el debido proceso", "cumple la norma constitucional", "consolida la jurisprudencia"],
            "v_intrans_p": ["garantizan la seguridad jurídica", "resguardan el debido proceso", "cumplen la norma constitucional", "consolidan la jurisprudencia"]
        },
        "medicine": {
            "n_ms": ["diagnóstico clínico", "protocolo terapéutico", "ensayo clínico", "marcador biológico", "cuadro sintomático", "tratamiento profiláctico", "examen analítico", "pronóstico médico", "agente patógeno"],
            "n_fs": ["terapia profiláctica", "farmacovigilancia", "conducta médica", "anamnesis detallada", "inmunidad celular", "fisiopatología", "respuesta inmune", "eficacia terapéutica", "remisión completa"],
            "n_mp": ["ensayos clínicos", "marcadores biológicos", "síntomas característicos", "agentes patógenos", "parámetros fisiológicos", "estudios aleatorizados"],
            "n_fp": ["respuestas inmunológicas", "terapias innovadoras", "intervenciones quirúrgicas", "evidencias científicas", "reacciones adversas"],
            "adj_ms": [" terapéutico", " clínico", " profiláctico", " fisiológico", " patógeno", " multidisciplinar", " asintomático"],
            "adj_fs": [" terapéutica", " clínica", " profiláctica", " fisiológica", " patógena", " multidisciplinar", " asintomática"],
            "adj_mp": [" terapéuticos", " clínicos", " profilácticos", " fisiológicos", " patógenos", " multidisciplinares"],
            "adj_fp": [" terapéuticas", " clínicas", " profilácticas", " fisiológicas", " patógenas", " multidisciplinares"],
            "v_trans_s": ["diagnostica ", "sintetiza ", "atenúa ", "rehabilita ", "prescribe ", "estabiliza ", "modula ", "inhibe "],
            "v_trans_p": ["diagnostican ", "sintetizan ", "atenúan ", "rehabilitan ", "prescriben ", "estabilizan ", "modulan ", "inhiben "],
            "v_intrans_s": ["potencia la respuesta inmune", "garantiza la eficacia terapéutica", "combate la patología", "asegura la recuperación clínica"],
            "v_intrans_p": ["potencian la respuesta inmune", "garantizan la eficacia terapéutica", "combaten la patología", "aseguran la recuperación clínica"]
        },
        "mining": {
            "n_ms": ["procesamiento de mineral", "ley de yacimiento", "plan de minado", "mapeo geotécnico", "procesamiento mineral", "depósito sedimentario", "conducto de javes", "estudio hidrogeológico"],
            "n_fs": ["explotación subterránea", "presa de javes", "prospección geológica", "explotación a cielo abierto", "geotecnia operativa", "recuperación de mina", "perforación rotativa"],
            "n_mp": ["residuos mineros", "parámetros geotécnicos", "cuerpos mineralizados", "métodos de extracción", "concentrados minerales", "estudios geológicos"],
            "n_fp": ["presas de contención", "reservas probadas", "estructuras geotécnicas", "rocas encajantes", "escavaciones mecánicas"],
            "adj_ms": [" mineral", " geotécnico", " geológico", " extractivo", " de alta ley", " hidrogeológico"],
            "adj_fs": [" mineral", " geotécnica", " geológica", " extractiva", " de alta ley", " hidrogeológica"],
            "adj_mp": [" minerales", " geotécnicos", " geológicos", " extractivos", " hidrogeológicos"],
            "adj_fp": [" minerales", " geotécnicas", " geológicas", " extractivas", " hidrogeológicas"],
            "v_trans_s": ["extrae ", "procesa ", "mapea ", "beneficia ", "estabiliza ", "optimiza ", "perfore ", "escava "],
            "v_trans_p": ["extraen ", "procesan ", "mapean ", "benefician ", "estabilizan ", "optimizan ", "perforan ", "escavan "],
            "v_intrans_s": ["aumenta la recuperación metalúrgica", "asegura la estabilidad geotécnica", "optimiza el ciclo minero", "maximiza el valor del yacimiento"],
            "v_intrans_p": ["aumentan la recuperación metalúrgica", "aseguran la estabilidad geotécnica", "optimizan el ciclo minero", "maximizan el valor del yacimiento"]
        },
        "politics": {
            "n_ms": ["pacto federal", "proceso legislativo", "presupuesto participativo", "escenario electoral", "debate parlamentar", "acuerdo político", "proyecto de ley", "quórum cualificado", "sistema multipartidista"],
            "n_fs": ["bancada parlamentaria", "reforma institucional", "coalición partidaria", "articulación política", "soberanía popular", "política pública", "diplomacia multilateral", "representación democrática", "enmienda constitucional"],
            "n_mp": ["derechos civiles", "acuerdos bilaterales", "proyectos de ley", "pactos institucionales", "mandatos representativos", "partidos políticos"],
            "n_fp": ["políticas públicas", "reformas estructurales", "coaliciones partidarias", "directrices gubernamentales", "comisiones parlamentarias"],
            "adj_ms": [" parlamentario", " legislativo", " democrático", " institucional", " gubernamental", " multipartidista", " diplomático"],
            "adj_fs": [" parlamentaria", " legislativa", " democrática", " institucional", " gubernamental", " multipartidista", " diplomática"],
            "adj_mp": [" parlamentarios", " legislativos", " democráticos", " institucionales", " gubernamentales"],
            "adj_fp": [" parlamentarias", " legislativas", " democráticas", " institucionales", " gubernamentales"],
            "v_trans_s": ["articula ", "promulga ", "sanciona ", "debate ", "pacta ", "delibera ", "vota ", "negocia "],
            "v_trans_p": ["articulan ", "promulgan ", "sancionan ", "debaten ", "pactan ", "deliberan ", "botan ", "negocian "],
            "v_intrans_s": ["fortalece la representación democrática", "promueve la estabilidad institucional", "consolida la participación popular", "asegura el consenso político"],
            "v_intrans_p": ["fortalecen la representación democrática", "promueven la estabilidad institucional", "consolidan la participación popular", "aseguran el consenso político"]
        },
        "technology": {
            "n_ms": ["modelo estructural", "desarrollo tecnológico", "plan estratégico", "diseño de negocio", "marco conceptual", "pipeline de integración", "dashboard analítico", "algoritmo predictivo", "servidor distribuido"],
            "n_fs": ["gobernanza corporativa", "disrupción tecnológica", "metodología ágil", "transformación digital", "sinergia organizacional", "arquitectura de microservicios", "inteligencia predicitiva", "infraestructura en la nube"],
            "n_mp": ["flujos de trabajo", "cuellos de botella", "mecanismos de control", "sistemas heredados", "requisitos no funcionales", "motores de crecimiento", "microservicios escalables"],
            "n_fp": ["actividades operativas", "metas estratégicas", "herramientas tecnológicas", "soluciones corporativas", "capacidades analíticas", "arquitecturas distribuidas"],
            "adj_ms": [" resiliente", " adaptativo", " sostenible", " disruptivo", " optimizado", " escalable", " innovador", " orientado a datos"],
            "adj_fs": [" resiliente", " adaptativa", " sostenible", " disruptiva", " optimizada", " escalable", " innovadora", " orientada a datos"],
            "adj_mp": [" resilientes", " adaptativos", " sostenibles", " disruptivos", " optimizados", " escalables"],
            "adj_fp": [" resilientes", " adaptativas", " sostenibles", " disruptivas", " optimizadas", " escalables"],
            "v_trans_s": ["exige ", "obliga ", "impulsa ", "optimiza ", "viabiliza ", "sustenta ", "desbloquea ", "despliega "],
            "v_trans_p": ["exigen ", "obligan ", "impulsan ", "optimizan ", "viabilizan ", "sustentan ", "desbloquean ", "despliegan "],
            "v_intrans_s": ["evoluciona continuamente", "progresa rápidamente", "se consolida en el mercado", "genera valor de largo plazo"],
            "v_intrans_p": ["evolucionan continuamente", "progresan rápidamente", "se consolidan en el mercado", "generan valor de largo plazo"]
        }
    },
    "fr": {
        "business": {
            "n_ms": ["plan stratégique", "plan d'affaires", "flux de trésorerie", "retour sur investissement", "positionnement sur le marché", "conseil d'administration", "équilibre financier", "accord commercial", "budget opérationnel", "capital d'exploitation", "développement pérenne", "rendement corporatif"],
            "n_fs": ["stratégie d'entreprise", "gestion des risques", "marge bénéficiaire", "gouvernance d'entreprise", "valeur ajoutée", "synergie opérationnelle", "rentabilité financière", "prise de décision", "croissance durable"],
            "n_mp": ["indicateurs financiers", "principaux actionnaires", "actifs stratégiques", "résultats d'exploitation", "plans de continuité", "marchés émergents", "fonds d'investissement", "coûts de structure"],
            "n_fp": ["orientations stratégiques", "opportunités de marché", "projections financières", "alliances commerciales", "structures de capital", "décisions managériales"],
            "adj_ms": [" stratégique", " corporatif", " financier", " rentable", " compétitif", " opérationnel", " scalable", " commercial"],
            "adj_fs": [" stratégique", " corporative", " financière", " rentable", " compétitive", " opérationnelle", " scalable", " commerciale"],
            "adj_mp": [" stratégiques", " corporatifs", " financiers", " rentables", " compétitifs", " opérationnels", " scalables"],
            "adj_fp": [" stratégiques", " corporatives", " financières", " rentables", " compétitives", " opérationnelles", " scalables"],
            "v_trans_s": ["maximise ", "stimule ", "optimise ", "consolide ", "dynamise ", "viabilise ", "structure ", "mitige "],
            "v_trans_p": ["maximisent ", "stimulent ", "optimisent ", "consolident ", "dynamisent ", "viabilisent ", "structurent ", "mitigent "],
            "v_intrans_s": ["maximise le retour sur investissement", "assure la solidité financière", "renforce le positionnement sur le marché", "génère de la valeur à long terme"],
            "v_intrans_p": ["maximisent le retour sur investissement", "assurent la solidité financière", "renforcent le positionnement sur le marché", "génèrent de la valeur à long terme"]
        },
        "ecology": {
            "n_ms": ["crédit carbone", "biome fragile", "écosystème durable", "impact écologique", "aménagement forestier", "développement durable", "bilan carbone", "cycle énergétique", "habitat naturel"],
            "n_fs": ["transition énergétique", "empreinte carbone", "biodiversité préservée", "conservation environnementale", "économie circulaire", "neutralité climatique", "gestion des déchets", "durabilité écologique"],
            "n_mp": ["ressources naturelles", "écosystèmes locaux", "indicateurs environnementaux", "crédits carbone", "habitats protégés", "déchets valorisés", "services écosystémiques"],
            "n_fp": ["énergies renouvelables", "cibles de décarbonation", "politiques environnementales", "zones protégées", "pratiques durables"],
            "adj_ms": [" durable", " écologique", " bas carbone", " renouvelable", " écoresponsable", " biodégradable"],
            "adj_fs": [" durable", " écologique", " bas carbone", " renouvelable", " écoresponsable", " biodégradable"],
            "adj_mp": [" durables", " écologiques", " bas carbone", " renouvelables", " écoresponsables"],
            "adj_fp": [" durables", " écologiques", " bas carbone", " renouvelables", " écoresponsables"],
            "v_trans_s": ["préserve ", "atténue ", "régénère ", "décarbonise ", "conserve ", "restaure ", "protège "],
            "v_trans_p": ["préservent ", "atténuent ", "régénèrent ", "décarbonisent ", "conservent ", "restaurent ", "protègent "],
            "v_intrans_s": ["favorise la neutralité climatique", "réduit l'impact environnemental", "renforce la biodiversité", "garantit l'équilibre écologique"],
            "v_intrans_p": ["favorisent la neutralité climatique", "réduisent l'impact environnemental", "renforcent la biodiversité", "garantissent l'équilibre écologique"]
        },
        "law": {
            "n_ms": ["respect du droit", "ordre juridique", "litige judiciaire", "cadre réglementaire", "avis juridique", "vice de forme", "recours contentieux", "jugement rendu", "dispositif légal"],
            "n_fs": ["jurisprudence établie", "sécurité juridique", "norme constitutionnelle", "procédure judiciaire", "présomption d'innocence", "mesure conservatoire", "décision définitive", "autorité de la chose jugée"],
            "n_mp": ["droits fondamentaux", "délais de recours", "précédents judiciaires", "textes de loi", "honoraires d'avocat", "actes juridiques"],
            "n_fp": ["garanties constitutionnelles", "règles de droit", "décisions interlocutoires", "mesures de sauvegarde", "prétentions juridiques"],
            "adj_ms": [" juridique", " constitutionnel", " procédural", " contraignant", " incontestable", " jurisprudentiel"],
            "adj_fs": [" juridique", " constitutionnelle", " procédurale", " contraignante", " incontestable", " jurisprudentielle"],
            "adj_mp": [" juridiques", " constitutionnels", " procéduraux", " contraignants", " incontestables"],
            "adj_fp": [" juridiques", " constitutionnelles", " procédurales", " contraignantes", " incontestables"],
            "v_trans_s": ["fonde ", "confirme ", "clarifie ", "prescrit ", "réglemente ", "garantit ", "défend "],
            "v_trans_p": ["fondent ", "confirment ", "clarifient ", "prescrivent ", "réglementent ", "garantissent ", "défendent "],
            "v_intrans_s": ["garantit la sécurité juridique", "préserve le procès équitable", "respecte la constitution", "consolide la jurisprudence"],
            "v_intrans_p": ["garantissent la sécurité juridique", "préservent le procès équitable", "respectent la constitution", "consolident la jurisprudence"]
        },
        "medicine": {
            "n_ms": ["diagnostic clinique", "protocole thérapeutique", "essai clinique", "marqueur biologique", "tableau clinique", "traitement préventif", "bilan biologique", "pronostic médical", "agent pathogène"],
            "n_fs": ["thérapie ciblée", "pharmacovigilance", "démarche médicale", "anamnèse complète", "immunité cellulaire", "physiopathologie", "réponse immunitaire", "efficacité thérapeutique"],
            "n_mp": ["essais cliniques", "marqueurs biologiques", "symptômes cliniques", "agents pathogènes", "paramètres physiologiques", "traitements palliatifs"],
            "n_fp": ["réponses immunitaires", "thérapies innovantes", "interventions chirurgicales", "preuves scientifiques", "réactions secondaires"],
            "adj_ms": [" thérapeutique", " clinique", " prophylactique", " physiologique", " pathogène", " pluridisciplinaire", " asymptomatique"],
            "adj_fs": [" thérapeutique", " clinique", " prophylactique", " physiologique", " pathogène", " pluridisciplinaire", " asymptomatique"],
            "adj_mp": [" thérapeutiques", " cliniques", " prophylactiques", " physiologiques", " pathogènes", " pluridisciplinaires"],
            "adj_fp": [" thérapeutiques", " cliniques", " prophylactiques", " physiologiques", " pathogènes", " pluridisciplinaires"],
            "v_trans_s": ["diagnostique ", "synthétise ", "atténue ", "réadapte ", "prescrit ", "stabilise ", "module ", "inhibe "],
            "v_trans_p": ["diagnostiquent ", "synthétisent ", "atténuent ", "réadaptent ", "prescrivent ", "stabilisent ", "modulent ", "inhibent "],
            "v_intrans_s": ["stimule la réponse immunitaire", "assure l'efficacité thérapeutique", "enraye l'évolution de la maladie", "garantit le rétablissement clinique"],
            "v_intrans_p": ["stimulent la réponse immunitaire", "assurent l'efficacité thérapeutique", "enrayent l'évolution de la maladie", "garantissent le rétablissement clinique"]
        },
        "mining": {
            "n_ms": ["traitement du minerai", "gisement exploitable", "plan d'extraction", "relevé géotechnique", "processus minéralurgique", "dépôt sédimentaire", "forage d'exploration"],
            "n_fs": ["exploitation souterraine", "digue de résidus", "prospection géologique", "mine à ciel ouvert", "stabilité géotechnique", "remise en état du site"],
            "n_mp": ["résidus miniers", "paramètres géotechniques", "corps minéralisés", "gisements découverts", "procédés d'extraction", "concentrés minéraux"],
            "n_fp": ["digues de retenue", "réserves prouvées", "structures géologiques", "roches encaissantes", "excavations minières"],
            "adj_ms": [" minier", " géotechnique", " géologique", " extractif", " métallifère", " sédimentaire"],
            "adj_fs": [" minière", " géotechnique", " géologique", " extractive", " métallifère", " sédimentaire"],
            "adj_mp": [" miniers", " géotechniques", " géologiques", " extractifs", " sédimentaires"],
            "adj_fp": [" minières", " géotechniques", " géologiques", " extractives", " sédimentaires"],
            "v_trans_s": ["extrait ", "traite ", "cartographie ", "stabilise ", "optimise ", "fore ", "échantillonne "],
            "v_trans_p": ["extraient ", "traitent ", "cartographient ", "stabilisent ", "optimisent ", "forent ", "échantillonnent "],
            "v_intrans_s": ["augmente la récupération métallurgique", "garantit la stabilité géotechnique", "optimise le cycle d'exploitation", "valorise le gisement"],
            "v_intrans_p": ["augmentent la récupération métallurgique", "garantissent la stabilité géotechnique", "optimisent le cycle d'exploitation", "valorisent le gisement"]
        },
        "politics": {
            "n_ms": ["pacte républicain", "processus législatif", "débat parlementaire", "scrutin électoral", "accord politique", "projet de loi", "dialogue social", "compromis partisan"],
            "n_fs": ["représentation démocratique", "réforme institutionnelle", "coalition majoritaire", "politique publique", "diplomatie multilatérale", "souveraineté populaire", "assemblée générale"],
            "n_mp": ["droits civiques", "accords bilatéraux", "débats publics", "mandats électifs", "partis politiques", "enjeux électoraux"],
            "n_fp": ["politiques publiques", "réformes structurelles", "coalitions politiques", "orientations gouvernementales", "commissions parlementaires"],
            "adj_ms": [" parlementaire", " législatif", " démocratique", " institutionnel", " gouvernemental", " multipartite", " diplomatique"],
            "adj_fs": [" parlementaire", " législative", " démocratique", " institutionnelle", " gouvernementale", " multipartite", " diplomatique"],
            "adj_mp": [" parlementaires", " législatifs", " démocratiques", " institutionnels", " gouvernementaux"],
            "adj_fp": [" parlementaires", " législatives", " démocratiques", " institutionnelles", " gouvernementales"],
            "v_trans_s": ["articule ", "promulgue ", "promut ", "débat ", "sanctionne ", "négocie ", "délibère ", "adopte "],
            "v_trans_p": ["articulent ", "promulguent ", "promuvent ", "débattent ", "sanctionnent ", "négocient ", "délibèrent ", "adoptent "],
            "v_intrans_s": ["renforce la légitimité démocratique", "favorise la stabilité institutionnelle", "garantit la participation citoyenne", "facilite le consensus politique"],
            "v_intrans_p": ["renforcent la légitimité démocratique", "favorisent la stabilité institutionnelle", "garantissent la participation citoyenne", "facilitent le consensus politique"]
        },
        "technology": {
            "n_ms": ["modèle architectural", "développement logiciel", "système distribué", "pipeline de déploiement", "tableau de bord prédictif", "algorithme d'apprentissage", "serveur applicatif"],
            "n_fs": ["gouvernance des données", "disruption numérique", "méthode agile", "transformation digitale", "architecture de microservices", "intelligence artificielle", "infrastructure cloud"],
            "n_mp": ["flux de données", "goulots d'étranglement", "systèmes patrimoniaux", "environnements conteneurisés", "microservices distribués", "clusters de calcul"],
            "n_fp": ["applications web", "solutions logicielles", "capacités analytiques", "infrastructures hybrides", "architectures événementielles"],
            "adj_ms": [" résilient", " adaptatif", " cloud-native", " disruptif", " conteneurisé", " scalable", " innovant", " orienté données"],
            "adj_fs": [" résiliente", " adaptative", " cloud-native", " disruptive", " conteneurisée", " scalable", " innovante", " orientée données"],
            "adj_mp": [" résilients", " adaptatifs", " cloud-natives", " disruptifs", " conteneurisés", " scalables"],
            "adj_fp": [" résilientes", " adaptatives", " cloud-natives", " disruptives", " conteneurisées", " scalables"],
            "v_trans_s": ["exige ", "pilote ", "stimule ", "optimise ", "sécurise ", "déploie ", "orchestre ", "accélère "],
            "v_trans_p": ["exigent ", "pilotent ", "stimulent ", "optimisent ", "sécurisent ", "déploient ", "orchestrent ", "accélèrent "],
            "v_intrans_s": ["évolue en continu", "progresse à grande échelle", "se standardise sur le marché", "réduit la latence opérationnelle"],
            "v_intrans_p": ["évoluent en continu", "progressent à grande échelle", "se standardisent sur le marché", "réduisent la latence opérationnelle"]
        }
    },
    "la": {
        "business": [
            "Negotiatio honesta et prudentia commercialis divitias civitatum stabiliunt.",
            "Consilium directivum prudenter opes et rationes societatis dispensat.",
            "Fides mercatorum et claritas pactorum fundamentum totius commercii constituunt.",
            "Lucrum iustum et aequum ex solido labore et providentia nascitur.",
            "Societates mercatoriae per maria et terras utilitatem publicam propagant.",
            "Aerarium publicum et privatae rationes accurate computatae stabilitatem praestant.",
            "Pacta conventa sine dolo malo semper servari oportet inter negotiatores.",
            "Prudentia in sumptibus et diligentia in operibus prosperitatem diuturnam efficiunt."
        ],
        "ecology": [
            "Natura inest in mentibus nostris ad conservandum omne genus animantium et herbarum.",
            "Rerum naturae cognitio pacem animo adferat et terrarum orbis salutem conservat.",
            "Elementa mundi, ignis, aqua, aer et terra, perpetuo in se recurrunt et renovantur.",
            "Sol et ventus aeternas vires praebent quibus terrae pulchritudo sustinetur.",
            "Arbores silvarum et flumina pura vitam cunctis creaturis generosis largiuntur.",
            "Conservatio terrarum et marium officium hominis sapientis semper fuit.",
            "Ecosystema terrae in concordia et stabili temperantia naturae consistit.",
            "Vires naturae in exhausto fonte renovationis perpetuae redundantes rurgent."
        ],
        "law": [
            "Jurisprudentia est divinarum atque humanarum rerum notitia, iusti atque iniusti scientia.",
            "Iustitia est constans et perpetua voluntas ius suum cuique tribuendi.",
            "Juris praecepta sunt haec: honeste vivere, alterum non laedere, suum cuique tribuere.",
            "Salus populi suprema lex esto et in omnibus iudiciis aequitas servetur.",
            "Nullum crimen, nulla poena sine praevia lege scripta et stricta.",
            "Pacta sunt servanda et fides publica in contractibus semper custodiri debet.",
            "In dubio pro reo iudicandum est et praesumptio innocentiae custodiri oportet.",
            "Audiatur et altera pars antequam iudex sententiam finalem pronuntiet."
        ],
        "medicine": [
            "Sanitas est status secundum naturam et omnium corporis partium compositio harmonica.",
            "Primum non nocere et aegroto salutem semper consilio ac studio adferre.",
            "Medicina est ars curationis quae mentem et corpus pariter confortat et sanat.",
            "Cibus sit medicina tua et medicina sit cibus tuus in omni vita.",
            "Contagionum causa in parvis corpusculis latet quae aere et aqua pervagantur.",
            "Diagnosis praevia et cura sedula morbos gravissimos saepe avertunt.",
            "Anamnesis diligens et observatio signorum vitalium praesidium vitae praebent.",
            "Pharmacopolia et herbae medicinales aegrotantium dolores celeriter leniunt."
        ],
        "mining": [
            "Metalla ex intimis terrae visceribus arte et labore hominum eruuntur.",
            "Aurum, argentum et ferrum in venis montium abscondita ad usum civitatum extrahuntur.",
            "Geometria et mechanica in fodinis regendis et concavitatibus sustinendis necessariae sunt.",
            "Lapides pretiosi et mineralia varia varietates naturae mirabiles demonstrant.",
            "Montes excavantur ut materiae valentes ad aedificia et instrumenta fabricanda reperiantur.",
            "Terrae opes cum cautione et ratione effodiendae sunt ut futuram posteritatem adiuvent.",
            "Venae orichalci et aeris in cavis saxosis inventae divitias urbibus adferunt.",
            "Securitas fossorum in cuniculis subterraneis semper prima cura praefecti esto."
        ],
        "politics": [
            "Res publica est res populi, cum bene ac iuste geritur a magistratibus prudentibus.",
            "Concordia parvae res crescunt, discordia maximae dilabuntur in civitate.",
            "Leges breves esse oportet ut ab omnibus civibus facilius teneantur et observentur.",
            "Libertas est potestas faciendi id quod iure licet et nemini servire.",
            "Populi imperium et senatus auctoritas in republica moderata consentire debent.",
            "Publica utilitas privatis commodis semper anteponenda est in consiliis urbis.",
            "Civitas bene ordinata pacem et prosperitatem cunctis incolis pariter praestat.",
            "Oratoris facultas et consilium senatorium libertatem reipublicae defendunt."
        ],
        "technology": [
            "Ars et scientia in machinis construendis humanam potentiam ultra fines auferunt.",
            "Firmitas, utilitas et venustas in omnibus operibus architecturalibus servandae sunt.",
            "Automata et instrumenta mechanica labores graves hominum levant et accelerant.",
            "Ratio numerorum et figurae geometricae fundamentum totius artis ingeniariae constituunt.",
            "Inventionum novarum usus vias novas ad prosperitatem civitatum aperit.",
            "Scientia et usus in unum collati miracula opera in terris perficiunt.",
            "Aquaelia et structurae hydraulicis ratione exquisita urbium aquam dispensant.",
            "Machinationes novae et rotae versatiles celeritatem operum summopere augent."
        ]
    }
}
